### ISSUE TITLE
Release naming

### ISSUE THREAD

**Issue by DocCyblade** [DocCyblade/tkl-rt#13]
I am thinking changing release names to align with TKL. Just need to figure out what they currently use.

I thought about using XX.#.A.B.C

XX.# would be the TKLDev/base app used to build the appliance.
A.B.C would be the release of RT

**Comment by DocCyblade** [comment]
After some thinking, the builds based on packages should not have a RT release because the package version could change. So it would install whatever is most current. If I use an upstream archive I should use A.B.C so that we know what is being downloaded since we can control that.

**Comment by DocCyblade** [comment]
The more I think about the version numbers really should only be about TKL release for this appliance. However if I do a upstream build, have the build number as part of the number would be good.

I really would like to have 4.2 but I think getting a 4.0 one up and running would be the best start. Then focus on a 4.2 since more than likely it will have to be a upstream install.

**Comment by DocCyblade** [comment]
Thinking going to change my number based on turnkey's TKLDev. 

If the release is based on packages only it will have the XX.X.# format.

XX.X.# - XX.X is the base appliance's version number, the # will be the revision of the build code.
     Example 13.2.2 - Would be based off of TKL 13.2 and would be release 2 

If the release is based on upstream archive, will use the XX.X.#.US.A.B.C-1

XX.X.US.A.B.C - XX.X is the base appliance's version number, the # will be the revision of the build code. US identifies as upstream archive used, and the A.B.C is the version upstream used.
Example 13.1.2.US.4.2.5 - Based on TKL 13.1, upstream archive v4.2.5 used, rev 2 of the applause build code.

**Comment by DocCyblade** [comment]
I have decided to use below naming scheme

If the release is based on packages only it will have the XX.X.# format.

XX.X.# - XX.X is the base appliance's version number, the # will be the revision of the build code.
Example 13.2.2 - Would be based off of TKL 13.2 and would be release 2

If the release is based on upstream archive, will use the XX.X.#.US.A.B.C-1

XX.X.US.A.B.C - XX.X is the base appliance's version number, the # will be the revision of the build code. US identifies as upstream archive used, and the A.B.C is the version upstream used.
Example 13.1.2.US.4.2.5 - Based on TKL 13.1, upstream archive v4.2.5 used, rev 2 of the applause build code.

**Comment by JedMeister** [comment]
Not that it probably really matters too much, but just thought I'd share with you my understanding of TurnKey plans for future releases. 

AFAIK post v13.1 (which hopefully will come one day...) TurnKey may at times release out of band updates (updated appliances that are released on their own, not as part of a full release) to images (e.g. if they have a show stopper bug that needs patching) and those out of band releases will be incremented similar to what you are suggesting. E.g. an update to a v13.1 appliance will be 13.1.1 or perhaps 13.1-1

Like I say it doesn't need to affect your planned naming convention, just thought I'd share... :)
